Repository acm-ucr/vex-robotics-website, pull requests merged in 2024-05, with the labels that each got.

#74 Created Subteam Data
  src/data/subteam.js
Labels: ready for review

#76 created about us page
  src/components/about/AboutUs.jsx
Labels: ready for review

#77 fixed footer
  src/components/Footer.jsx
Labels: ready for review

#83 Javier/update vex
  public/assets/CrossBar.svg
  public/assets/DotBar.svg
  src/components/Vex.jsx
Labels: ready for review, responsive

#82 fixing landing page responsiveness
  src/components/Title.jsx
  src/components/landing/Landing.jsx
Labels: ready for review, responsive

#80 built event page
  src/app/events/page.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/Events.jsx
Labels: ready for review

#79 Fixed subteam images
  src/components/about/Subteams.jsx
  src/data/subteam.js
  src/data/subteams.js
Labels: bug, ready for review

#84 mobile navBar spacing
  src/components/Navigation.jsx
Labels: responsive

#85 Media Component
  .eslintignore
  .gitignore
  .husky/pre-commit
  .prettierignore
  public/assets/BottomPattern.svg
  public/assets/DiscordLogo.svg
  public/assets/EmailLogo.svg
  public/assets/InstagramLogo.svg
  public/assets/JoinUs.svg
  public/assets/LeftPattern.svg
  public/assets/LinkedInLogo.svg
  public/assets/RightPattern.svg
  public/assets/UCR.svg
  public/assets/VEXROBOTICS.svg
  public/assets/logo.svg
  public/svg/Polymaker.svg
  public/svg/Worthington.svg
  src/components/media/Media.jsx
Labels: ready for review

#93 fixed sponsors text size
  .husky/pre-commit
  src/components/home/Sponsors.jsx
Labels: enhancement, ready for review, responsive

#97 Kevinloritsch/aboutResponsive
  src/components/Navigation.jsx
  src/components/SubteamTag.jsx
  src/components/about/AboutUs.jsx
  src/components/about/Subteam.jsx
  src/components/about/Subteams.jsx
Labels: ready for review

#98 Kevinloritsch/calendarResponsive
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomHeader.jsx
  src/components/calendar/CustomToolbar.jsx
Labels: ready for review

#99 changed footer icons to map through footer.js, attempted responsiveness
  src/components/Footer.jsx
  src/data/footer.js
Labels: ready for review

#101 fix home bug
  src/components/SubteamTag.jsx
  src/data/navigation.js
Labels: ready for review

#102 added Event Card component
  src/components/calendar/EventCard.jsx
Labels: ready for review

#103 Make Boards.jsx responsive
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
Labels: ready for review, responsive

#96 Add/remove margin
  src/components/Companies.jsx
  src/components/Footer.jsx
Labels: ready for review

#75 About Us header component file
  public/assets/PurpleBar.svg
  src/components/about/AboutHeader.jsx
Labels: ready for review

#105 Added purple bar to bottom of each page
  src/app/about/page.js
  src/app/events/page.js
  src/app/page.js
  src/app/team/page.js
Labels: enhancement

#106 added bars to about us and sponsors
  src/components/Header.jsx
  src/components/about/AboutUs.jsx
  src/components/home/Sponsors.jsx
Labels: ready for review

#100 Made subteams responsive
  src/components/about/Subteam.jsx
Labels: ready for review, responsive

#104 Fix NavBar Logo Overflow
  src/components/Navigation.jsx
Labels: ready for review, responsive

#118 Animated About Page
  package-lock.json
  src/components/about/AboutUs.jsx
  src/components/about/Subteams.jsx
  src/data/subteam.js
Labels: ready for review, animate

#119 statement
  package-lock.json
  src/app/team/page.js
Labels: ready for review

#120 button to about page
  src/app/about/page.js
Labels: ready for review

#121 Added animation to all media on initial load
  package-lock.json
  src/app/media/page.js
  src/components/media/Media.jsx
  src/components/media/Medias.jsx
Labels: ready for review, animate

#126 Changed logo
  src/app/favicon.ico
  src/app/icon.ico
Labels: ready for review

#127 Added media, event, team header
  src/app/events/page.js
  src/app/media/page.js
  src/app/team/page.js
Labels: ready for review

#128 header
  src/components/Header.jsx
Labels: ready for review

#129 added animated button in media
  src/app/events/page.js
  src/app/media/page.js
Labels: ready for review

#130 Fix Teams Error , Maybe . I hope so :(
  src/components/board/Board.jsx
  src/data/boards.js
Labels: bug

#139 Fixed mobile overflow
  src/components/about/Subteams.jsx
Labels: bug, ready for review, responsive

#140 changed footer mobile responsive
  src/components/Footer.jsx
Labels: ready for review, responsive

#142 Animated Landing
  src/components/landing/Landing.jsx
Labels: ready for review, animate

#145 Animate Boards
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
Labels: ready for review, animate

#158 Added Hover for Media
  src/components/media/Media.jsx
  src/components/media/Medias.jsx
Labels: ready for review, animate

#159 centered our sponsors on mobile
  src/components/Header.jsx
Labels: ready for review, responsive

#160 added social media links to footer
  src/data/footer.js
Labels: ready for review

#167 added text to about us
  src/components/about/AboutUs.jsx
Labels: ready for review

#163 Kevinloritsch/shortenBar
  src/components/Header.jsx
Labels: ready for review

#162 directed join button to discord
  src/components/landing/Landing.jsx
Labels: ready for review

#144 calendar API
  package-lock.json
  src/app/events/page.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/Events.jsx
  src/components/events/Event.jsx
  src/components/events/Events.jsx
Labels: question, ready for review

#168 fixes for events component
  src/components/events/Events.jsx
Labels: bug, ready for review

#169 removed comma next to default string
  src/components/events/Events.jsx
Labels: bug, ready for review
