Repository acm-ucr/vex-robotics-website, pull requests merged in 2024-04, with the labels that each got.

#29 updating dependencies
  package-lock.json
  package.json
Labels: question

#23 added in tailwindcss animated package
  package-lock.json
  package.json
  tailwind.config.js
Labels: address comments

#27 adds placeholder vex text and image
  src/components/Vex.jsx
Labels: ready for review

#30 Created button component
  src/components/Button.jsx
Labels: ready for review

#33 Nimrah/subteam
  src/components/SubteamTag.jsx
Labels: ready for review

#37 added a navigation bar
  package-lock.json
  package.json
  public/assets/logo.webp
  src/components/Navigation.jsx
  src/data/navigation.js
Labels: ready for review

#39 Kevinloritsch/appDirectory
  src/app/about/page.js
  src/app/events/page.js
  src/app/media/page.js
  src/app/team/page.js
  src/components/board/Team.jsx
  src/components/calendar/Events.jsx
Labels: ready for review

#40 added AboutUs component
  src/components/about/AboutUs.jsx
Labels: ready for review

#42 added Board component
  src/components/board/Board.jsx
Labels: ready for review

#41 Kevinloritsch/calendar
  package-lock.json
  package.json
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/CustomHeader.jsx
  src/components/calendar/CustomToolbar.jsx
  src/components/calendar/Modal.jsx
  src/components/calendar/index.css
Labels: ready for review

#32 Created Title.jsx in components
  package-lock.json
  src/app/page.js
  src/components/Title.jsx
Labels: ready for review

#36 Created Subteam component
  src/components/about/Subteam.jsx
Labels: ready for review

#43 10 landing component
  package-lock.json
  public/assets/JoinUs.svg
  public/assets/UCR.svg
  public/assets/VEXROBOTICS.svg
  public/images/vexrobo.webp
  src/app/page.js
  src/components/Title.jsx
  src/components/landing/Landing.jsx
Labels: ready for review

#47 Created footer
  public/assets/BottomPattern.svg
  public/assets/DiscordLogo.svg
  public/assets/EmailLogo.svg
  public/assets/InstagramLogo.svg
  public/assets/LeftPattern.svg
  public/assets/LinkedInLogo.svg
  public/assets/RightPattern.svg
  src/app/layout.js
  src/components/Footer.jsx
Labels: ready for review

#56 added responsiveness to navbar elements
  src/components/Navigation.jsx
Labels: ready for review, responsive

#57 Created Subteams component
  src/components/about/Subteam.jsx
  src/components/about/Subteams.jsx
  src/data/subteams.js
Labels: ready for review

#62 Made Vex.js responsive
  src/components/Vex.jsx
Labels: responsive

#59 Made responsive companies
  src/components/Companies.jsx
Labels: responsive

#61 added Boards component
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
  src/data/boards.js
Labels: ready for review

#63 Sponsors Component
  src/components/home/Sponsors.jsx
Labels: ready for review

#64 Build out Page.js (in progress)
  src/app/page.js
Labels: ready for review
