Repository acm-ucr/vex-robotics-website, pull requests merged in 2024-06, with the labels that each got.

#161 added photo to about us page
  public/images/VexRoboticsClubPhoto.webp
  src/components/about/AboutUs.jsx
Labels: ready for review

#171 contact us button leads to mail
  src/app/about/page.js
  src/app/events/page.js
  src/app/media/page.js
Labels: ready for review

#165 Added text to subteams
  src/data/subteam.js
Labels: help wanted

#164 linked sponor button
  src/components/home/Sponsors.jsx
Labels: ready for review

#175 Upgrade calendar
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/EventCard.jsx
  src/components/calendar/Modal.jsx
  src/components/calendar/index.css
Labels: enhancement, ready for review
